<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GAozbnG' shared service.

return $this->privates['.service_locator.GAozbnG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ServiceController::createEmploye' => ['privates', '.service_locator.EwHjoYh', 'get_ServiceLocator_EwHjoYhService.php', true],
    'App\\Controller\\ServiceController::createService' => ['privates', '.service_locator.gYChNGw', 'get_ServiceLocator_GYChNGwService.php', true],
    'App\\Controller\\ServiceController::lister' => ['privates', '.service_locator.Sot0AXx', 'get_ServiceLocator_Sot0AXxService.php', true],
    'App\\Controller\\ServiceController::supEmploye' => ['privates', '.service_locator.EwHjoYh', 'get_ServiceLocator_EwHjoYhService.php', true],
    'App\\Controller\\ServiceController::supService' => ['privates', '.service_locator.gYChNGw', 'get_ServiceLocator_GYChNGwService.php', true],
    'App\\Controller\\ServiceController:createEmploye' => ['privates', '.service_locator.EwHjoYh', 'get_ServiceLocator_EwHjoYhService.php', true],
    'App\\Controller\\ServiceController:createService' => ['privates', '.service_locator.gYChNGw', 'get_ServiceLocator_GYChNGwService.php', true],
    'App\\Controller\\ServiceController:lister' => ['privates', '.service_locator.Sot0AXx', 'get_ServiceLocator_Sot0AXxService.php', true],
    'App\\Controller\\ServiceController:supEmploye' => ['privates', '.service_locator.EwHjoYh', 'get_ServiceLocator_EwHjoYhService.php', true],
    'App\\Controller\\ServiceController:supService' => ['privates', '.service_locator.gYChNGw', 'get_ServiceLocator_GYChNGwService.php', true],
], [
    'App\\Controller\\ServiceController::createEmploye' => '?',
    'App\\Controller\\ServiceController::createService' => '?',
    'App\\Controller\\ServiceController::lister' => '?',
    'App\\Controller\\ServiceController::supEmploye' => '?',
    'App\\Controller\\ServiceController::supService' => '?',
    'App\\Controller\\ServiceController:createEmploye' => '?',
    'App\\Controller\\ServiceController:createService' => '?',
    'App\\Controller\\ServiceController:lister' => '?',
    'App\\Controller\\ServiceController:supEmploye' => '?',
    'App\\Controller\\ServiceController:supService' => '?',
]);
