<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Sot0AXx' shared service.

return $this->privates['.service_locator.Sot0AXx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'employe' => ['privates', '.errored..service_locator.Sot0AXx.App\\Entity\\Employe', NULL, 'Cannot autowire service ".service_locator.Sot0AXx": it references class "App\\Entity\\Employe" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'employe' => 'App\\Entity\\Employe',
    'manager' => '?',
]);
