<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2LNTv8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2LNTv8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF2LNTv8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF2LNTv8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF2LNTv8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F2LNTv8',
    'container.build_id' => '1323fe8a',
    'container.build_time' => 1562968005,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2LNTv8');
