<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT6BKSz1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT6BKSz1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerT6BKSz1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerT6BKSz1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerT6BKSz1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'T6BKSz1',
    'container.build_id' => '755d4ed0',
    'container.build_time' => 1563191346,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT6BKSz1');
